#!/usr/bin/env bash

# ================
# = YABAI config =
# ================


#
# pre-setting
#
# sudo /opt/homebrew/bin/yabai --load-sa
# /opt/homebrew/bin/yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


# default layout: [bsp, float], or check docs
/opt/homebrew/bin/yabai -m config layout float


# padding
yabai -m config \
    mouse_follows_focus on \
    window_animation_duration 0.0 \
    window_animation_frame_rate 120


# rules
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
