-- TODO: doesn't work, no idea why
return {
  -- {
  --   "stevearc/conform.nvim",
  --   opts = {
  --     formatters = {
  --       prettier = {
  --         prepend_args = {
  --           "--print-width",
  --           "160",
  --           "--semi",
  --           "--tab-width",
  --           "2",
  --           "--single-quote",
  --           "--trailing-comma",
  --           "all",
  --           "--arrow-parens",
  --           "always",
  --           "--bracket-spacing",
  --           "--end-of-line",
  --           "lf",
  --           "--html-whitespace-sensitivity",
  --           "css",
  --           "--embedded-language-formatting",
  --           "auto",
  --           "--prose-wrap",
  --           "preserve",
  --           "--jsx-bracket-same-line",
  --           "false",
  --           "--bracket-same-line",
  --           "false",
  --           "--quote-props",
  --           "as-needed",
  --           "--single-attribute-per-line",
  --           "--vue-indent-script-and-style",
  --           "false",
  --         },
  --       },
  --     },
  --   },
  -- },
}
